services:
  db:
    image: mariadb:10.7
    volumes:
      - dbdata:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: backlink
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5


  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 run:app
    depends_on:
      db:
        condition: service_healthy      #  ⬅️ bekle
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:userpass@db:3306/backlink?charset=utf8mb4

volumes:
  dbdata: