services:
  db:
    image: mariadb:10.7
    volumes:
      - dbdata:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: Asli281019*Cagdas
      MYSQL_DATABASE: backlink
      MYSQL_USER: user
      MYSQL_PASSWORD: Asli281019*Cagdas
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5


  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 15 && gunicorn --bind 0.0.0.0:5000 run:app"
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:Asli281019*Cagdas@db:3306/backlink?charset=utf8mb4

volumes:
  dbdata: