"""add has_comment

Revision ID: d7b65f06fee3
Revises: 
Create Date: 2025-04-07 03:39:43.922202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7b65f06fee3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_comment_form', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=False)
        batch_op.alter_column('keyword',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_site', schema=None) as batch_op:
        batch_op.alter_column('keyword',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('has_comment_form')

    # ### end Alembic commands ###
